function incr = mins_update(z,i,j,n,deltaP,deltaM)

incr = [0;0];
h = 1/n;

a = z(2,3)-z(2,2); b = z(2,3)-z(3,3);
c = z(2,2)-z(3,2); d = z(3,3)-z(3,2);
e = z(1,2)-z(1,1); g = z(1,2)-z(2,2);
p = z(1,1)-z(2,1); q = z(2,2)-z(2,1);

%positive search direction
incr(1) = (deltaP^2-2*deltaP*a)/(sqrt(h^2+(a-deltaP)^2+b^2)+sqrt(h^2+a^2+b^2)) + ...
       (deltaP^2+2*deltaP*c)/(sqrt(h^2+(c+deltaP)^2+d^2)+sqrt(h^2+c^2+d^2)) + ...
       (deltaP^2-2*deltaP*g)/(sqrt(h^2+(g-deltaP)^2+e^2)+sqrt(h^2+g^2+e^2)) + ...
       (deltaP^2+2*deltaP*q)/(sqrt(h^2+(q+deltaP)^2+p^2)+sqrt(h^2+q^2+p^2)) + ...
       (2*deltaP*(deltaP-g-a))/(sqrt(h^2+(g-deltaP)^2+(a-deltaP)^2)+sqrt(h^2+g^2+a^2)) + ...
       (2*deltaP*(deltaP+q+c))/(sqrt(h^2+(q+deltaP)^2+(c+deltaP)^2)+sqrt(h^2+q^2+c^2));
incr(1) = .5*h*incr(1);

%negative search direction
incr(2) = (deltaM^2+2*deltaM*a)/(sqrt(h^2+(a+deltaM)^2+b^2)+sqrt(h^2+a^2+b^2)) + ...
       (deltaM^2-2*deltaM*c)/(sqrt(h^2+(c-deltaM)^2+d^2)+sqrt(h^2+c^2+d^2)) + ...
       (deltaM^2+2*deltaM*g)/(sqrt(h^2+(g+deltaM)^2+e^2)+sqrt(h^2+g^2+e^2)) + ...
       (deltaM^2-2*deltaM*q)/(sqrt(h^2+(q-deltaM)^2+p^2)+sqrt(h^2+q^2+p^2)) + ...
       (2*deltaM*(deltaM+g+a))/(sqrt(h^2+(g+deltaM)^2+(a+deltaM)^2)+sqrt(h^2+g^2+a^2)) + ...
       (2*deltaM*(deltaM-q-c))/(sqrt(h^2+(q-deltaM)^2+(c-deltaM)^2)+sqrt(h^2+q^2+c^2));  
incr(2) = .5*h*incr(2);